version: '3.8'

services:
  ai-backend:
    build:
      context: .
      dockerfile: Dockerfile.ai-backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    volumes:
      - ./kanban.db:/app/data/kanban.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AI_BACKEND_URL=http://ai-backend:8000
    depends_on:
      - ai-backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
